# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: root
  password: root

development:
  <<: *default
  database: r14-team-82_development

test:
  <<: *default
  database: r14-team-82_test

production:
  <<: *default
  database: r14-team-82_production
